name: 'analytics_engineering_group_four'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
test-paths: ["tests"]
analysis-paths: ["analysis"]

# Default config for all models
models:
  analytics_engineering_group_four:
    bronze:
      +schema: bronze
      +materialized: table

    
    silver:
      +schema: silver
      +materialized: table

    gold:
      +schema: gold
      +materialized: table
