version: 2

sources:
  - name: raw            # dbt name you’ll use 
    database: DQOCASC3M52OC_DB      # Snowflake database name
    schema: inventory        # Snowflake schema name
    tables:
      - name: suppliers         # dbt name you’ll use in source()
        description: "This table contains all supppliers details"
      
      - name: products
        description: "This table contains all products details"

      - name: stock_levels
        description: "This table contains all stock_levels details"

      - name: stock_movements
        description: "This table contains all stock_movements details"

      - name: warehouses
        description: "This table contains all warehouses details"                

